/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AutomationRegistrarInterface } from "./AutomationRegistrarInterface";
export type { GraviolaRegisterUpkeep } from "./GraviolaRegisterUpkeep";
