/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface AIOracleCallbackReceiverInterface extends Interface {
  getFunction(
    nameOrSignature: "aiOracle" | "aiOracleCallback" | "isFinalized"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "aiOracle", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "aiOracleCallback",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isFinalized",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "aiOracle", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "aiOracleCallback",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isFinalized",
    data: BytesLike
  ): Result;
}

export interface AIOracleCallbackReceiver extends BaseContract {
  connect(runner?: ContractRunner | null): AIOracleCallbackReceiver;
  waitForDeployment(): Promise<this>;

  interface: AIOracleCallbackReceiverInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  aiOracle: TypedContractMethod<[], [string], "view">;

  aiOracleCallback: TypedContractMethod<
    [requestId: BigNumberish, output: BytesLike, callbackData: BytesLike],
    [void],
    "nonpayable"
  >;

  isFinalized: TypedContractMethod<
    [requestId: BigNumberish],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "aiOracle"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "aiOracleCallback"
  ): TypedContractMethod<
    [requestId: BigNumberish, output: BytesLike, callbackData: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isFinalized"
  ): TypedContractMethod<[requestId: BigNumberish], [boolean], "view">;

  filters: {};
}
