/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as graviolaRegisterUpkeepSol from "./GraviolaRegisterUpkeep.sol";
export type { graviolaRegisterUpkeepSol };
export type { AIOracleCallbackReceiver } from "./AIOracleCallbackReceiver";
export type { AIOracleMock } from "./AIOracleMock";
export type { Graviola } from "./Graviola";
export type { GraviolaMetadata } from "./GraviolaMetadata";
export type { GraviolaNonFungible } from "./GraviolaNonFungible";
export type { GraviolaWell } from "./GraviolaWell";
export type { IAIOracle } from "./IAIOracle";
export type { IKeeperRegistry } from "./IKeeperRegistry";
export type { VRFConsumer } from "./VRFConsumer";
export type { VRFHostConsumerInterface } from "./VRFHostConsumerInterface";
export type { VRFHostMock } from "./VRFHostMock";
